[package]
name = "driver-rust"
version = "0.1.0"
authors = ["Josh Delman <joshdelman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysfs_gpio = "0.5"
